site_name: Nogu documentation
theme:
  name: 'material'
  palette:
    primary: blue
  favicon: imgs/favicon.png
  logo: imgs/icon_logo.png
  features:
    - content.code.annotate
    - diagrams

plugins:
  - search:
  - git-revision-date-localized:
      fallback_to_build_date: true

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
